- name: Deploy Maven Project
  hosts: web
  become: yes

  tasks:
    - name: Copy JAR file
      copy:
        src: target/myapp-1.0-SNAPSHOT.jar
        dest: /opt/myapp-1.0-SNAPSHOT.jar

    - name: Run Application
      shell: nohup java -jar /opt/myapp-1.0-SNAPSHOT.jar > /tmp/myapp.log 2>&1 &
